
import { Board, Comment, Project, Ticket, User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    avatar: 'https://ui-avatars.com/api/?name=John+Doe',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatar: 'https://ui-avatars.com/api/?name=Jane+Smith',
    role: 'developer',
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    avatar: 'https://ui-avatars.com/api/?name=Bob+Johnson',
    role: 'manager',
  },
  {
    id: '4',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    avatar: 'https://ui-avatars.com/api/?name=Alice+Brown',
    role: 'developer',
  },
  {
    id: '5',
    name: 'Charlie Wilson',
    email: 'charlie.wilson@example.com',
    avatar: 'https://ui-avatars.com/api/?name=Charlie+Wilson',
    role: 'viewer',
  },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Redesign the company website with modern UI/UX',
    key: 'WEB',
    lead: users[0],
    members: [users[0], users[1], users[3]],
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-06-20'),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Develop a new mobile app for iOS and Android',
    key: 'MOB',
    lead: users[2],
    members: [users[2], users[1], users[3], users[4]],
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-07-05'),
  },
];

// Sample comments
const comments: Comment[] = [
  {
    id: '1',
    author: users[1],
    content: 'I\'ve started working on this. Should be done by tomorrow.',
    createdAt: new Date('2023-05-10T14:30:00'),
  },
  {
    id: '2',
    author: users[0],
    content: 'Looks great! Let me know if you need any help.',
    createdAt: new Date('2023-05-10T15:45:00'),
  },
];

export const sampleTickets: Ticket[] = [
  {
    id: '1',
    key: 'WEB-1',
    summary: 'Implement new header design',
    description: 'Update the header component with the new design from Figma.',
    status: 'in-progress',
    priority: 'high',
    issueType: 'task',
    assignee: users[1],
    reporter: users[0],
    project: projects[0],
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2023-05-15'),
    comments: comments,
  },
  {
    id: '2',
    key: 'WEB-2',
    summary: 'Add authentication pages',
    description: 'Create login, signup, and forgot password pages.',
    status: 'todo',
    priority: 'medium',
    issueType: 'feature',
    assignee: users[3],
    reporter: users[0],
    project: projects[0],
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2023-05-12'),
    comments: [],
  },
  {
    id: '3',
    key: 'WEB-3',
    summary: 'Optimize image loading',
    description: 'Implement lazy loading for images to improve performance.',
    status: 'backlog',
    priority: 'high',
    issueType: 'task',
    assignee: users[1],
    reporter: users[0],
    project: projects[0],
    createdAt: new Date('2023-05-13'),
    updatedAt: new Date('2023-05-13'),
    comments: [],
  },
  {
    id: '4',
    key: 'WEB-4',
    summary: 'Fix mobile navigation issues',
    description: 'Address reported navigation problems on mobile devices.',
    status: 'review',
    priority: 'high',
    issueType: 'task',
    assignee: users[3],
    reporter: users[0],
    project: projects[0],
    createdAt: new Date('2023-05-14'),
    updatedAt: new Date('2023-05-16'),
    comments: [],
  },
  {
    id: '5',
    key: 'WEB-5',
    summary: 'Update footer links',
    description: 'Update the footer links according to the new sitemap.',
    status: 'done',
    priority: 'medium',
    issueType: 'task',
    assignee: users[1],
    reporter: users[0],
    project: projects[0],
    createdAt: new Date('2023-05-08'),
    updatedAt: new Date('2023-05-11'),
    comments: [],
  },
  {
    id: '6',
    key: 'MOB-1',
    summary: 'Setup project architecture',
    description: 'Define the app architecture and setup the initial project.',
    status: 'in-progress',
    priority: 'high',
    issueType: 'epic',
    assignee: users[2],
    reporter: users[2],
    project: projects[1],
    createdAt: new Date('2023-04-10'),
    updatedAt: new Date('2023-04-12'),
    comments: [],
  },
  {
    id: '7',
    key: 'MOB-2',
    summary: 'Implement user profile screen',
    description: 'Create the user profile screen with edit capabilities.',
    status: 'done',
    priority: 'high',
    issueType: 'story',
    assignee: users[1],
    reporter: users[2],
    project: projects[1],
    createdAt: new Date('2023-04-15'),
    updatedAt: new Date('2023-04-22'),
    comments: [],
  },
  {
    id: '8',
    key: 'MOB-3',
    summary: 'Add push notifications',
    description: 'Integrate push notifications for both iOS and Android.',
    status: 'todo',
    priority: 'medium',
    issueType: 'feature',
    assignee: users[3],
    reporter: users[2],
    project: projects[1],
    createdAt: new Date('2023-04-18'),
    updatedAt: new Date('2023-04-18'),
    comments: [],
  },
];

export const sampleBoard: Board = {
  id: 'board-1',
  name: 'Website Redesign Board',
  project: projects[0],
  columns: [
    {
      id: 'backlog',
      title: 'Backlog',
      tickets: sampleTickets.filter(t => t.status === 'backlog' && t.project.id === '1'),
    },
    {
      id: 'todo',
      title: 'To Do',
      tickets: sampleTickets.filter(t => t.status === 'todo' && t.project.id === '1'),
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      tickets: sampleTickets.filter(t => t.status === 'in-progress' && t.project.id === '1'),
    },
    {
      id: 'review',
      title: 'Review',
      tickets: sampleTickets.filter(t => t.status === 'review' && t.project.id === '1'),
    },
    {
      id: 'done',
      title: 'Done',
      tickets: sampleTickets.filter(t => t.status === 'done' && t.project.id === '1'),
    },
  ],
};
