// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eherbforfqzkspptnhwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZXJiZm9yZnF6a3NwcHRuaHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NjgxNDMsImV4cCI6MjA1NjU0NDE0M30.E3kqF7y1oONBk1d4SatHjPMAcBEBQQlMF0dna0V4bsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);